[package]
name = "flindeeered"
version = "0.1.0"
compiler = "0.12.0"
entrypoint = "lib.typ"
authors = ["Terpity", "Typst GmbH <https://typst.app>"]
license = "MIT-0"
description = "A derivative of Typst's [charged-ieee](https://github.com/typst/templates/tree/main/charged-ieee), formatted to match Flinders' standards. Adapted by Harrison Wren, 2025"
keywords = ["Institute of Electrical and Electronics Engineers", "IEEE", "Electrical Engineering", "Computer Science", "Computer Engineering", "Software", "Flinders"]
categories = ["paper"]
disciplines = ["computer-science", "engineering"]

[template]
path = "template"
entrypoint = "main.typ"
